In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os
os.listdir('/content/drive/MyDrive/sales_analysis_project/data')

Mounted at /content/drive

['sales_analysis_dataset.csv', 'cleaned_sales.csv']

In [ ]:
import pandas as pd

file_path = "/content/drive/MyDrive/sales_analysis_project/data/sales_analysis_dataset.csv"
df = pd.read_csv(file_path)

df.head()

,Order ID,Order Date,Region,Category,Product,Sales,Profit,Quantity,Customer
0,ORD1000,2023-01-01,South,Technology,Chair,761.84,234.56,5,Customer_C
1,ORD1001,2023-01-02,Central,Technology,Storage,1879.63,43.19,4,Customer_A
2,ORD1002,2023-01-03,East,Furniture,Binder,174.45,-53.61,8,Customer_C
3,ORD1003,2023-01-04,South,Furniture,Laptop,894.10,205.75,6,Customer_B
4,ORD1004,2023-01-05,South,Office Supplies,Phone,1938.40,39.09,6,Customer_C

In [ ]:
#understand data

df.info()
print(df.describe())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order ID    200 non-null    object
 1   Order Date  200 non-null    object
 2   Region      200 non-null    object
 3   Category    200 non-null    object
 4   Product     200 non-null    object
 5   Sales       200 non-null    float64
 6   Profit      200 non-null    float64
 7   Quantity    200 non-null    int64
 8   Customer    200 non-null    object
dtypes: float64(2), int64(1), object(6)
memory usage: 14.2+ KB
             Sales      Profit    Quantity
count   200.000000  200.000000  200.000000
mean   1072.955300  157.412000    4.985000
std     545.443523  190.125556    2.590042
min     125.980000 -198.180000    1.000000
25%     602.435000   31.197500    3.000000
50%    1085.080000  174.630000    5.000000
75%    1528.197500  307.367500    7.000000
max    1992.270000  498.380000    9.000000
Order ID      0
Order Date    0
Region        0
Category      0
Product       0
Sales         0
Profit        0
Quantity      0
Customer      0
dtype: int64

In [ ]:
#cleaning data

df.duplicated().sum()
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Order Date']

#create new columns
df['Year'] = df['Order Date'].dt.year
df['Year']
df['Month'] = df['Order Date'].dt.month
df['Month']
df['Month Name'] = df['Order Date'].dt.month_name()
df['Month Name']
df.head(5)

#create profit margin
df['Profit Margin'] = df['Profit'] / df['Sales']
df['Profit Margin']
print(df.head())

#data validation
print(df[df['Sales'] <= 0])
print(df[df['Profit'].isnull()])

  Order ID Order Date   Region         Category  Product    Sales  Profit  \
0  ORD1000 2023-01-01    South       Technology    Chair   761.84  234.56
1  ORD1001 2023-01-02  Central       Technology  Storage  1879.63   43.19
2  ORD1002 2023-01-03     East        Furniture   Binder   174.45  -53.61
3  ORD1003 2023-01-04    South        Furniture   Laptop   894.10  205.75
4  ORD1004 2023-01-05    South  Office Supplies    Phone  1938.40   39.09

   Quantity    Customer  Year  Month Month Name  Profit Margin
0         5  Customer_C  2023      1    January       0.307886
1         4  Customer_A  2023      1    January       0.022978
2         8  Customer_C  2023      1    January      -0.307309
3         6  Customer_B  2023      1    January       0.230120
4         6  Customer_C  2023      1    January       0.020166
Empty DataFrame
Columns: [Order ID, Order Date, Region, Category, Product, Sales, Profit, Quantity, Customer, Year, Month, Month Name, Profit Margin]
Index: []
Empty DataFrame
Columns: [Order ID, Order Date, Region, Category, Product, Sales, Profit, Quantity, Customer, Year, Month, Month Name, Profit Margin]
Index: []

In [ ]:
#exploratory data analysis
print("Total Sales:", df['Sales'].sum())
print("Total Profit:", df['Profit'].sum())

#sales by category
df.groupby('Category')['Sales'].sum().sort_values(ascending=False)

#sales by region
df.groupby('Region')['Sales'].sum().sort_values(ascending=False)

#monthly sales trend
df.groupby('Month Name')['Sales'].sum()

#top 5 customers
df.groupby('Customer')['Sales'].sum().sort_values(ascending=False).head()

#top products
df.groupby('Product')['Sales'].sum().sort_values(ascending=False)

Total Sales: 214591.06
Total Profit: 31482.4

Product
Table      47161.39
Binder     37264.06
Storage    36648.19
Phone      35865.23
Chair      34658.06
Laptop     22994.13
Name: Sales, dtype: float64

In [ ]:
#save cleaned data
df.to_csv("/content/drive/MyDrive/sales_analysis_project/data/cleaned_sales.csv", index=False)

In [ ]:
#load cleaned data
import pandas as pd

file_path = "/content/drive/MyDrive/sales_analysis_project/data/cleaned_sales.csv"
df = pd.read_csv(file_path)

df.head()

,Order ID,Order Date,Region,Category,Product,Sales,Profit,Quantity,Customer,Year,Month,Month Name,Profit Margin
0,ORD1000,2023-01-01,South,Technology,Chair,761.84,234.56,5,Customer_C,2023,1,January,0.307886
1,ORD1001,2023-01-02,Central,Technology,Storage,1879.63,43.19,4,Customer_A,2023,1,January,0.022978
2,ORD1002,2023-01-03,East,Furniture,Binder,174.45,-53.61,8,Customer_C,2023,1,January,-0.307309
3,ORD1003,2023-01-04,South,Furniture,Laptop,894.10,205.75,6,Customer_B,2023,1,January,0.230120
4,ORD1004,2023-01-05,South,Office Supplies,Phone,1938.40,39.09,6,Customer_C,2023,1,January,0.020166

In [ ]:
#load cleaned data into sql
import sqlite3

conn = sqlite3.connect('sales.db')
df.to_sql('sales', conn, if_exists='replace', index=False)

#check data
query = "SELECT * FROM sales LIMIT 5"
pd.read_sql(query, conn)

#total sales
query = "SELECT SUM(Sales) AS Total_Sales FROM sales"
pd.read_sql(query, conn)

#sales by category
query = """
SELECT Category, SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Category
ORDER BY Total_Sales DESC
"""
pd.read_sql(query, conn)

#profit by region
query = """
SELECT Region, SUM(Profit) AS Total_Profit
FROM sales
GROUP BY Region
ORDER BY Total_Profit DESC
"""
print(pd.read_sql(query,conn))

#Top 5 products
query = """
SELECT Product, SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Product
ORDER BY Total_Sales DESC
LIMIT 5
"""
pd.read_sql(query,conn)

#monthly sales trend
query = """
SELECT Month, SUM(Sales) AS Monthly_Sales
FROM sales
GROUP BY Month
ORDER BY Month
"""
pd.read_sql(query,conn)

#high profit orders
query = """
SELECT *
FROM sales
WHERE Profit > 300
"""
pd.read_sql(query,conn)

    Region  Total_Profit
0    South       9231.26
1     West       7914.42
2     East       7896.17
3  Central       6440.55

,Order ID,Order Date,Region,Category,Product,Sales,Profit,Quantity,Customer,Year,Month,Month Name,Profit Margin
0,ORD1013,2023-01-14,South,Technology,Table,1747.52,412.02,4,Customer_A,2023,1,January,0.235774
1,ORD1015,2023-01-16,East,Technology,Table,553.33,481.18,8,Customer_B,2023,1,January,0.869608
2,ORD1018,2023-01-19,Central,Office Supplies,Table,552.65,375.25,1,Customer_B,2023,1,January,0.679001
3,ORD1025,2023-01-26,West,Office Supplies,Chair,201.62,425.95,7,Customer_C,2023,1,January,2.112638
4,ORD1036,2023-02-06,Central,Office Supplies,Binder,1152.04,407.81,3,Customer_C,2023,2,February,0.353989
5,ORD1039,2023-02-09,South,Furniture,Chair,1584.46,490.38,9,Customer_A,2023,2,February,0.309493
6,ORD1041,2023-02-11,South,Technology,Binder,1868.77,446.83,9,Customer_C,2023,2,February,0.239104
7,ORD1043,2023-02-13,Central,Technology,Chair,1992.27,331.97,9,Customer_C,2023,2,February,0.166629
8,ORD1045,2023-02-15,Central,Office Supplies,Storage,1500.37,304.36,9,Customer_B,2023,2,February,0.202857
9,ORD1050,2023-02-20,South,Technology,Table,1690.23,391.11,2,Customer_B,2023,2,February,0.231395
10,ORD1051,2023-02-21,West,Technology,Storage,1747.05,324.73,7,Customer_A,2023,2,February,0.185873
11,ORD1053,2023-02-23,Central,Furniture,Chair,909.57,407.05,2,Customer_A,2023,2,February,0.447519
12,ORD1057,2023-02-27,East,Office Supplies,Storage,378.55,316.18,8,Customer_D,2023,2,February,0.835240
13,ORD1060,2023-03-02,South,Office Supplies,Storage,1204.48,388.50,4,Customer_D,2023,3,March,0.322546
14,ORD1070,2023-03-12,West,Office Supplies,Binder,1439.66,315.78,7,Customer_B,2023,3,March,0.219343
15,ORD1076,2023-03-18,Central,Office Supplies,Storage,1185.80,429.75,6,Customer_A,2023,3,March,0.362414
16,ORD1081,2023-03-23,Central,Technology,Phone,1393.97,453.58,1,Customer_B,2023,3,March,0.325387
17,ORD1086,2023-03-28,West,Technology,Storage,1103.90,395.57,1,Customer_B,2023,3,March,0.358339
18,ORD1088,2023-03-30,Central,Furniture,Chair,1624.01,364.11,3,Customer_D,2023,3,March,0.224204
19,ORD1090,2023-04-01,Central,Office Supplies,Phone,1156.41,389.62,1,Customer_C,2023,4,April,0.336922
20,ORD1094,2023-04-05,West,Furniture,Table,1846.32,498.08,6,Customer_D,2023,4,April,0.269769
21,ORD1095,2023-04-06,West,Furniture,Binder,580.68,427.63,1,Customer_C,2023,4,April,0.736430
22,ORD1097,2023-04-08,Central,Office Supplies,Chair,243.33,442.18,6,Customer_D,2023,4,April,1.817203
23,ORD1099,2023-04-10,East,Technology,Binder,511.94,482.55,4,Customer_C,2023,4,April,0.942591
24,ORD1101,2023-04-12,West,Technology,Table,1992.08,306.03,8,Customer_A,2023,4,April,0.153623
25,ORD1102,2023-04-13,West,Office Supplies,Table,1424.16,374.60,7,Customer_A,2023,4,April,0.263032
26,ORD1103,2023-04-14,Central,Technology,Chair,829.98,302.92,7,Customer_B,2023,4,April,0.364973
27,ORD1106,2023-04-17,West,Technology,Storage,1921.53,387.01,2,Customer_A,2023,4,April,0.201407
28,ORD1108,2023-04-19,West,Furniture,Binder,849.59,477.60,7,Customer_D,2023,4,April,0.562154
29,ORD1111,2023-04-22,South,Furniture,Binder,422.39,315.37,7,Customer_D,2023,4,April,0.746632
30,ORD1114,2023-04-25,South,Furniture,Binder,535.85,337.45,9,Customer_C,2023,4,April,0.629747
31,ORD1117,2023-04-28,West,Technology,Table,593.90,452.41,8,Customer_C,2023,4,April,0.761761
32,ORD1132,2023-05-13,East,Furniture,Phone,1148.02,356.00,4,Customer_B,2023,5,May,0.310099
33,ORD1134,2023-05-15,South,Technology,Table,881.38,395.51,6,Customer_D,2023,5,May,0.448739
34,ORD1135,2023-05-16,East,Technology,Binder,1577.44,322.18,5,Customer_B,2023,5,May,0.204242
35,ORD1137,2023-05-18,East,Office Supplies,Chair,1972.04,453.06,2,Customer_C,2023,5,May,0.229742
36,ORD1138,2023-05-19,South,Furniture,Storage,815.80,493.65,7,Customer_A,2023,5,May,0.605112
37,ORD1141,2023-05-22,East,Office Supplies,Table,1675.41,448.51,7,Customer_A,2023,5,May,0.267702
38,ORD1142,2023-05-23,Central,Office Supplies,Table,1181.25,305.12,5,Customer_B,2023,5,May,0.258303
39,ORD1144,2023-05-25,Central,Office Supplies,Binder,169.96,347.06,3,Customer_C,2023,5,May,2.042010
40,ORD1145,2023-05-26,South,Furniture,Phone,354.32,379.56,4,Customer_B,2023,5,May,1.071235
41,ORD1146,2023-05-27,South,Technology,Table,125.98,325.35,2,Customer_C,2023,5,May,2.582553
42,ORD1147,2023-05-28,South,Furniture,Phone,243.18,359.68,2,Customer_A,2023,5,May,1.479069
43,ORD1148,2023-05-29,East,Furniture,Table,1414.26,377.59,1,Customer_C,2023,5,May,0.266988
44,ORD1152,2023-06-02,East,Office Supplies,Chair,1211.78,435.51,3,Customer_D,2023,6,June,0.359397
45,ORD1158,2023-06-08,East,Furniture,Phone,577.74,429.77,6,Customer_C,2023,6,June,0.743881
46,ORD1171,2023-06-21,East,Office Supplies,Phone,1939.15,311.38,3,Customer_C,2023,6,June,0.160576
47,ORD1174,2023-06-24,Central,Furniture,Chair,1220.92,415.04,8,Customer_A,2023,6,June,0.339940
48,ORD1176,2023-06-26,South,Office Supplies,Laptop,899.02,319.02,9,Customer_C,2023,6,June,0.354853
49,ORD1178,2023-06-28,East,Technology,Binder,1314.79,498.38,9,Customer_C,2023,6,June,0.379057
50,ORD1179,2023-06-29,South,Office Supplies,Binder,1629.58,326.68,6,Customer_D,2023,6,June,0.200469
51,ORD1181,2023-07-01,South,Office Supplies,Storage,1272.80,345.00,4,Customer_C,2023,7,July,0.271056
52,ORD1186,2023-07-06,West,Furniture,Laptop,272.90,328.24,2,Customer_D,2023,7,July,1.202785
53,ORD1196,2023-07-16,West,Technology,Chair,1699.97,340.32,7,Customer_A,2023,7,July,0.200192